### ISSUE TITLE
Remove debug code

### ISSUE THREAD

**Issue by ianshward** [mapbox/report-dt#12]
This looks like debug code, should it be removed?  https://github.com/mapbox/report-dt/blob/dev/server.js#L23

**Comment by Rub21** [comment]
@ianshward  it help for see , if the server.js is running:
![screenshot from 2015-02-24 15 50 02](https://cloud.githubusercontent.com/assets/1152236/6358912/f4535b1e-bc3c-11e4-8b31-6e532ff2e2d1.png)
 

but is not really necessary.

**Comment by Rub21** [comment]
@ianshward  it was removed .https://github.com/mapbox/report-dt/blob/dev/server.js#L23,

Close here

**Comment by ianshward** [comment]
Sorry I misread. I thought you allowed the port to be configured but then
had a fixed port in the debug.  That debug is fine to leave if it is
helpful.

Maybe a separate issue - should the port be configurable?
