### ISSUE TITLE
Use environment variables for PG connection

### ISSUE THREAD

**Issue by ianshward** [mapbox/report-dt#13]
Here https://github.com/mapbox/report-dt/blob/dev/server.js#L17-L22

instead of argv.user, argv.port, etc., you could use [postgres environment variables](http://www.postgresql.org/docs/8.4/static/libpq-envars.html) which may give people more flexibility in handling these credentials on their server.

**Comment by Rub21** [comment]
Done:
![screenshot from 2015-02-24 16 07 35](https://cloud.githubusercontent.com/assets/1152236/6359189/4a047a6e-bc3f-11e4-838e-30259a4e4925.png)

close here.
