### ISSUE TITLE
install.sh still relevant?

### ISSUE THREAD

**Issue by lxbarth** [mapbox/report-dt#3]
@Rub21 - looking at https://github.com/mapbox/report-dt/blob/mb-pages/install.sh I don't think it's relevant anymore.

- Calls `npm install` in a directory that does not contain a `package.json` file
- Let's not have platform specific `install.sh` files in a repo, running this on Mac OSX will just fail. To keep it simple, let's just document installation in README instead #2

**Comment by Rub21** [comment]
@lxbarth : I removed that file in this commit https://github.com/mapbox/report-dt/commit/0981256358dadd99eb97ecf62d1a701f43a1f4a1
